# Generated by Django 3.1.5 on 2021-01-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210110_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transacton_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=5),
            preserve_default=False,
        ),
    ]
