# Generated by Django 3.1.5 on 2021-01-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transaction_transacton_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
