# Generated by Django 3.1.5 on 2021-01-13 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210110_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactiondate',
            field=models.DateField(default=datetime.date(2021, 1, 13)),
        ),
    ]
